//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientUintTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IScanServer")]
    public interface IScanServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/DoWork", ReplyAction="http://tempuri.org/IScanServer/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/DoWork", ReplyAction="http://tempuri.org/IScanServer/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/GetCount", ReplyAction="http://tempuri.org/IScanServer/GetCountResponse")]
        string GetCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/GetCount", ReplyAction="http://tempuri.org/IScanServer/GetCountResponse")]
        System.Threading.Tasks.Task<string> GetCountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScanServerChannel : ClientUintTest.ServiceReference1.IScanServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScanServerClient : System.ServiceModel.ClientBase<ClientUintTest.ServiceReference1.IScanServer>, ClientUintTest.ServiceReference1.IScanServer {
        
        public ScanServerClient() {
        }
        
        public ScanServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScanServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetCount() {
            return base.Channel.GetCount();
        }
        
        public System.Threading.Tasks.Task<string> GetCountAsync() {
            return base.Channel.GetCountAsync();
        }
    }
}
