//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanInHead", Namespace="http://schemas.datacontract.org/2004/07/Lonking.CN.JGYFScanWcfService.Modal")]
    [System.SerializableAttribute()]
    public partial class ScanInHead : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ScanCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testClient.ServiceReference1.ScanInEntry[] ScanEntrysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScantimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNo {
            get {
                return this.DocNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNoField, value) != true)) {
                    this.DocNoField = value;
                    this.RaisePropertyChanged("DocNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ScanCount {
            get {
                return this.ScanCountField;
            }
            set {
                if ((this.ScanCountField.Equals(value) != true)) {
                    this.ScanCountField = value;
                    this.RaisePropertyChanged("ScanCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testClient.ServiceReference1.ScanInEntry[] ScanEntrys {
            get {
                return this.ScanEntrysField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanEntrysField, value) != true)) {
                    this.ScanEntrysField = value;
                    this.RaisePropertyChanged("ScanEntrys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Scantime {
            get {
                return this.ScantimeField;
            }
            set {
                if ((this.ScantimeField.Equals(value) != true)) {
                    this.ScantimeField = value;
                    this.RaisePropertyChanged("Scantime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanInEntry", Namespace="http://schemas.datacontract.org/2004/07/Lonking.CN.JGYFScanWcfService.Modal")]
    [System.SerializableAttribute()]
    public partial class ScanInEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testClient.ServiceReference1.ScanInHead ScanInHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScanInHeadIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemModel {
            get {
                return this.ItemModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemModelField, value) != true)) {
                    this.ItemModelField = value;
                    this.RaisePropertyChanged("ItemModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testClient.ServiceReference1.ScanInHead ScanInHead {
            get {
                return this.ScanInHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanInHeadField, value) != true)) {
                    this.ScanInHeadField = value;
                    this.RaisePropertyChanged("ScanInHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScanInHeadID {
            get {
                return this.ScanInHeadIDField;
            }
            set {
                if ((this.ScanInHeadIDField.Equals(value) != true)) {
                    this.ScanInHeadIDField = value;
                    this.RaisePropertyChanged("ScanInHeadID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sn {
            get {
                return this.SnField;
            }
            set {
                if ((object.ReferenceEquals(this.SnField, value) != true)) {
                    this.SnField = value;
                    this.RaisePropertyChanged("Sn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanOutHead", Namespace="http://schemas.datacontract.org/2004/07/Lonking.CN.JGYFScanWcfService.Modal")]
    [System.SerializableAttribute()]
    public partial class ScanOutHead : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ScanCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testClient.ServiceReference1.ScanOutEntry[] ScanEntrysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScantimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCode {
            get {
                return this.CustomerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCodeField, value) != true)) {
                    this.CustomerCodeField = value;
                    this.RaisePropertyChanged("CustomerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNo {
            get {
                return this.DocNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNoField, value) != true)) {
                    this.DocNoField = value;
                    this.RaisePropertyChanged("DocNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ScanCount {
            get {
                return this.ScanCountField;
            }
            set {
                if ((this.ScanCountField.Equals(value) != true)) {
                    this.ScanCountField = value;
                    this.RaisePropertyChanged("ScanCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testClient.ServiceReference1.ScanOutEntry[] ScanEntrys {
            get {
                return this.ScanEntrysField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanEntrysField, value) != true)) {
                    this.ScanEntrysField = value;
                    this.RaisePropertyChanged("ScanEntrys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Scantime {
            get {
                return this.ScantimeField;
            }
            set {
                if ((this.ScantimeField.Equals(value) != true)) {
                    this.ScantimeField = value;
                    this.RaisePropertyChanged("Scantime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScanOutEntry", Namespace="http://schemas.datacontract.org/2004/07/Lonking.CN.JGYFScanWcfService.Modal")]
    [System.SerializableAttribute()]
    public partial class ScanOutEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testClient.ServiceReference1.ScanOutHead ScanOutHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCodeField, value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemModel {
            get {
                return this.ItemModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemModelField, value) != true)) {
                    this.ItemModelField = value;
                    this.RaisePropertyChanged("ItemModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testClient.ServiceReference1.ScanOutHead ScanOutHead {
            get {
                return this.ScanOutHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanOutHeadField, value) != true)) {
                    this.ScanOutHeadField = value;
                    this.RaisePropertyChanged("ScanOutHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sn {
            get {
                return this.SnField;
            }
            set {
                if ((object.ReferenceEquals(this.SnField, value) != true)) {
                    this.SnField = value;
                    this.RaisePropertyChanged("Sn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vwICBill_8", Namespace="http://schemas.datacontract.org/2004/07/Lonking.CN.JGYFScanWcfService.Modal.K3Mod" +
        "al")]
    [System.SerializableAttribute()]
    public partial class vwICBill_8 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FAuxPlanPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FBatchNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FBillerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FCUUnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FCancellationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FCheckFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FChkPassItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FClosingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FConsignAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FConsignPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FDCSPIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FDCStockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FEntryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FEntrySupplyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FFManagerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FHookFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FInterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIsVMIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FKFDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FKFPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FMapNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FMapNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FOrgBillInterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FPlanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FRelateBrIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSManagerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSaleStyleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FShortNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSourceBillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FSourceTranTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FSupplyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUnitGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FVchInterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FVoucherFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FZPInterIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FauxpriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FauxqtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FbillNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FcheckeridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FcuQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FmodelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FAuxPlanPrice {
            get {
                return this.FAuxPlanPriceField;
            }
            set {
                if ((this.FAuxPlanPriceField.Equals(value) != true)) {
                    this.FAuxPlanPriceField = value;
                    this.RaisePropertyChanged("FAuxPlanPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBatchNo {
            get {
                return this.FBatchNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FBatchNoField, value) != true)) {
                    this.FBatchNoField = value;
                    this.RaisePropertyChanged("FBatchNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBillerID {
            get {
                return this.FBillerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FBillerIDField, value) != true)) {
                    this.FBillerIDField = value;
                    this.RaisePropertyChanged("FBillerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FCUUnitID {
            get {
                return this.FCUUnitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FCUUnitIDField, value) != true)) {
                    this.FCUUnitIDField = value;
                    this.RaisePropertyChanged("FCUUnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FCancellation {
            get {
                return this.FCancellationField;
            }
            set {
                if ((object.ReferenceEquals(this.FCancellationField, value) != true)) {
                    this.FCancellationField = value;
                    this.RaisePropertyChanged("FCancellation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FCheckFlag {
            get {
                return this.FCheckFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FCheckFlagField, value) != true)) {
                    this.FCheckFlagField = value;
                    this.RaisePropertyChanged("FCheckFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FChkPassItem {
            get {
                return this.FChkPassItemField;
            }
            set {
                if ((object.ReferenceEquals(this.FChkPassItemField, value) != true)) {
                    this.FChkPassItemField = value;
                    this.RaisePropertyChanged("FChkPassItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FClosing {
            get {
                return this.FClosingField;
            }
            set {
                if ((object.ReferenceEquals(this.FClosingField, value) != true)) {
                    this.FClosingField = value;
                    this.RaisePropertyChanged("FClosing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FConsignAmount {
            get {
                return this.FConsignAmountField;
            }
            set {
                if ((this.FConsignAmountField.Equals(value) != true)) {
                    this.FConsignAmountField = value;
                    this.RaisePropertyChanged("FConsignAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FConsignPrice {
            get {
                return this.FConsignPriceField;
            }
            set {
                if ((this.FConsignPriceField.Equals(value) != true)) {
                    this.FConsignPriceField = value;
                    this.RaisePropertyChanged("FConsignPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FDCSPID {
            get {
                return this.FDCSPIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FDCSPIDField, value) != true)) {
                    this.FDCSPIDField = value;
                    this.RaisePropertyChanged("FDCSPID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FDCStockID {
            get {
                return this.FDCStockIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FDCStockIDField, value) != true)) {
                    this.FDCStockIDField = value;
                    this.RaisePropertyChanged("FDCStockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FEntryID {
            get {
                return this.FEntryIDField;
            }
            set {
                if ((this.FEntryIDField.Equals(value) != true)) {
                    this.FEntryIDField = value;
                    this.RaisePropertyChanged("FEntryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FEntrySupply {
            get {
                return this.FEntrySupplyField;
            }
            set {
                if ((object.ReferenceEquals(this.FEntrySupplyField, value) != true)) {
                    this.FEntrySupplyField = value;
                    this.RaisePropertyChanged("FEntrySupply");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FFManagerID {
            get {
                return this.FFManagerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FFManagerIDField, value) != true)) {
                    this.FFManagerIDField = value;
                    this.RaisePropertyChanged("FFManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FHookFlag {
            get {
                return this.FHookFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FHookFlagField, value) != true)) {
                    this.FHookFlagField = value;
                    this.RaisePropertyChanged("FHookFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FInterID {
            get {
                return this.FInterIDField;
            }
            set {
                if ((this.FInterIDField.Equals(value) != true)) {
                    this.FInterIDField = value;
                    this.RaisePropertyChanged("FInterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FIsVMI {
            get {
                return this.FIsVMIField;
            }
            set {
                if ((object.ReferenceEquals(this.FIsVMIField, value) != true)) {
                    this.FIsVMIField = value;
                    this.RaisePropertyChanged("FIsVMI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FItemID {
            get {
                return this.FItemIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FItemIDField, value) != true)) {
                    this.FItemIDField = value;
                    this.RaisePropertyChanged("FItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FKFDate {
            get {
                return this.FKFDateField;
            }
            set {
                if ((this.FKFDateField.Equals(value) != true)) {
                    this.FKFDateField = value;
                    this.RaisePropertyChanged("FKFDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FKFPeriod {
            get {
                return this.FKFPeriodField;
            }
            set {
                if ((this.FKFPeriodField.Equals(value) != true)) {
                    this.FKFPeriodField = value;
                    this.RaisePropertyChanged("FKFPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FMapName {
            get {
                return this.FMapNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FMapNameField, value) != true)) {
                    this.FMapNameField = value;
                    this.RaisePropertyChanged("FMapName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FMapNumber {
            get {
                return this.FMapNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FMapNumberField, value) != true)) {
                    this.FMapNumberField = value;
                    this.RaisePropertyChanged("FMapNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FNote {
            get {
                return this.FNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.FNoteField, value) != true)) {
                    this.FNoteField = value;
                    this.RaisePropertyChanged("FNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FNumber {
            get {
                return this.FNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FNumberField, value) != true)) {
                    this.FNumberField = value;
                    this.RaisePropertyChanged("FNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FOrgBillInterID {
            get {
                return this.FOrgBillInterIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FOrgBillInterIDField, value) != true)) {
                    this.FOrgBillInterIDField = value;
                    this.RaisePropertyChanged("FOrgBillInterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FPlanAmount {
            get {
                return this.FPlanAmountField;
            }
            set {
                if ((this.FPlanAmountField.Equals(value) != true)) {
                    this.FPlanAmountField = value;
                    this.RaisePropertyChanged("FPlanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FQty {
            get {
                return this.FQtyField;
            }
            set {
                if ((this.FQtyField.Equals(value) != true)) {
                    this.FQtyField = value;
                    this.RaisePropertyChanged("FQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FRelateBrID {
            get {
                return this.FRelateBrIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FRelateBrIDField, value) != true)) {
                    this.FRelateBrIDField = value;
                    this.RaisePropertyChanged("FRelateBrID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSManagerID {
            get {
                return this.FSManagerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FSManagerIDField, value) != true)) {
                    this.FSManagerIDField = value;
                    this.RaisePropertyChanged("FSManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSaleStyle {
            get {
                return this.FSaleStyleField;
            }
            set {
                if ((object.ReferenceEquals(this.FSaleStyleField, value) != true)) {
                    this.FSaleStyleField = value;
                    this.RaisePropertyChanged("FSaleStyle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FShortNumber {
            get {
                return this.FShortNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FShortNumberField, value) != true)) {
                    this.FShortNumberField = value;
                    this.RaisePropertyChanged("FShortNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSourceBillNo {
            get {
                return this.FSourceBillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FSourceBillNoField, value) != true)) {
                    this.FSourceBillNoField = value;
                    this.RaisePropertyChanged("FSourceBillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FSourceTranType {
            get {
                return this.FSourceTranTypeField;
            }
            set {
                if ((this.FSourceTranTypeField.Equals(value) != true)) {
                    this.FSourceTranTypeField = value;
                    this.RaisePropertyChanged("FSourceTranType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FSupplyID {
            get {
                return this.FSupplyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FSupplyIDField, value) != true)) {
                    this.FSupplyIDField = value;
                    this.RaisePropertyChanged("FSupplyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUnitGroupID {
            get {
                return this.FUnitGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FUnitGroupIDField, value) != true)) {
                    this.FUnitGroupIDField = value;
                    this.RaisePropertyChanged("FUnitGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUnitID {
            get {
                return this.FUnitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FUnitIDField, value) != true)) {
                    this.FUnitIDField = value;
                    this.RaisePropertyChanged("FUnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FVchInterID {
            get {
                return this.FVchInterIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FVchInterIDField, value) != true)) {
                    this.FVchInterIDField = value;
                    this.RaisePropertyChanged("FVchInterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FVoucherFlag {
            get {
                return this.FVoucherFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FVoucherFlagField, value) != true)) {
                    this.FVoucherFlagField = value;
                    this.RaisePropertyChanged("FVoucherFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FZPInterID {
            get {
                return this.FZPInterIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FZPInterIDField, value) != true)) {
                    this.FZPInterIDField = value;
                    this.RaisePropertyChanged("FZPInterID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Famount {
            get {
                return this.FamountField;
            }
            set {
                if ((this.FamountField.Equals(value) != true)) {
                    this.FamountField = value;
                    this.RaisePropertyChanged("Famount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fauxprice {
            get {
                return this.FauxpriceField;
            }
            set {
                if ((this.FauxpriceField.Equals(value) != true)) {
                    this.FauxpriceField = value;
                    this.RaisePropertyChanged("Fauxprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Fauxqty {
            get {
                return this.FauxqtyField;
            }
            set {
                if ((this.FauxqtyField.Equals(value) != true)) {
                    this.FauxqtyField = value;
                    this.RaisePropertyChanged("Fauxqty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FbillNo {
            get {
                return this.FbillNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FbillNoField, value) != true)) {
                    this.FbillNoField = value;
                    this.RaisePropertyChanged("FbillNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fcheckerid {
            get {
                return this.FcheckeridField;
            }
            set {
                if ((object.ReferenceEquals(this.FcheckeridField, value) != true)) {
                    this.FcheckeridField = value;
                    this.RaisePropertyChanged("Fcheckerid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FcuQty {
            get {
                return this.FcuQtyField;
            }
            set {
                if ((this.FcuQtyField.Equals(value) != true)) {
                    this.FcuQtyField = value;
                    this.RaisePropertyChanged("FcuQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fdate {
            get {
                return this.FdateField;
            }
            set {
                if ((this.FdateField.Equals(value) != true)) {
                    this.FdateField = value;
                    this.RaisePropertyChanged("Fdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fmodel {
            get {
                return this.FmodelField;
            }
            set {
                if ((object.ReferenceEquals(this.FmodelField, value) != true)) {
                    this.FmodelField = value;
                    this.RaisePropertyChanged("Fmodel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IScanServer")]
    public interface IScanServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/DoWork", ReplyAction="http://tempuri.org/IScanServer/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/DoWork", ReplyAction="http://tempuri.org/IScanServer/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/GetCount", ReplyAction="http://tempuri.org/IScanServer/GetCountResponse")]
        string GetCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/GetCount", ReplyAction="http://tempuri.org/IScanServer/GetCountResponse")]
        System.Threading.Tasks.Task<string> GetCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanIn", ReplyAction="http://tempuri.org/IScanServer/ScanInResponse")]
        string ScanIn(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanIn", ReplyAction="http://tempuri.org/IScanServer/ScanInResponse")]
        System.Threading.Tasks.Task<string> ScanInAsync(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanOut", ReplyAction="http://tempuri.org/IScanServer/ScanOutResponse")]
        string ScanOut(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanOut", ReplyAction="http://tempuri.org/IScanServer/ScanOutResponse")]
        System.Threading.Tasks.Task<string> ScanOutAsync(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanInWCE", ReplyAction="http://tempuri.org/IScanServer/ScanInWCEResponse")]
        string ScanInWCE(testClient.ServiceReference1.ScanInHead scanInHead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanInWCE", ReplyAction="http://tempuri.org/IScanServer/ScanInWCEResponse")]
        System.Threading.Tasks.Task<string> ScanInWCEAsync(testClient.ServiceReference1.ScanInHead scanInHead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanOutWCE", ReplyAction="http://tempuri.org/IScanServer/ScanOutWCEResponse")]
        string ScanOutWCE(testClient.ServiceReference1.ScanOutHead scanOutHead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/ScanOutWCE", ReplyAction="http://tempuri.org/IScanServer/ScanOutWCEResponse")]
        System.Threading.Tasks.Task<string> ScanOutWCEAsync(testClient.ServiceReference1.ScanOutHead scanOutHead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/GetSaleBillInfo", ReplyAction="http://tempuri.org/IScanServer/GetSaleBillInfoResponse")]
        testClient.ServiceReference1.vwICBill_8[] GetSaleBillInfo(string billNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanServer/GetSaleBillInfo", ReplyAction="http://tempuri.org/IScanServer/GetSaleBillInfoResponse")]
        System.Threading.Tasks.Task<testClient.ServiceReference1.vwICBill_8[]> GetSaleBillInfoAsync(string billNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScanServerChannel : testClient.ServiceReference1.IScanServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScanServerClient : System.ServiceModel.ClientBase<testClient.ServiceReference1.IScanServer>, testClient.ServiceReference1.IScanServer {
        
        public ScanServerClient() {
        }
        
        public ScanServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScanServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetCount() {
            return base.Channel.GetCount();
        }
        
        public System.Threading.Tasks.Task<string> GetCountAsync() {
            return base.Channel.GetCountAsync();
        }
        
        public string ScanIn(System.IO.Stream stream) {
            return base.Channel.ScanIn(stream);
        }
        
        public System.Threading.Tasks.Task<string> ScanInAsync(System.IO.Stream stream) {
            return base.Channel.ScanInAsync(stream);
        }
        
        public string ScanOut(System.IO.Stream stream) {
            return base.Channel.ScanOut(stream);
        }
        
        public System.Threading.Tasks.Task<string> ScanOutAsync(System.IO.Stream stream) {
            return base.Channel.ScanOutAsync(stream);
        }
        
        public string ScanInWCE(testClient.ServiceReference1.ScanInHead scanInHead) {
            return base.Channel.ScanInWCE(scanInHead);
        }
        
        public System.Threading.Tasks.Task<string> ScanInWCEAsync(testClient.ServiceReference1.ScanInHead scanInHead) {
            return base.Channel.ScanInWCEAsync(scanInHead);
        }
        
        public string ScanOutWCE(testClient.ServiceReference1.ScanOutHead scanOutHead) {
            return base.Channel.ScanOutWCE(scanOutHead);
        }
        
        public System.Threading.Tasks.Task<string> ScanOutWCEAsync(testClient.ServiceReference1.ScanOutHead scanOutHead) {
            return base.Channel.ScanOutWCEAsync(scanOutHead);
        }
        
        public testClient.ServiceReference1.vwICBill_8[] GetSaleBillInfo(string billNo) {
            return base.Channel.GetSaleBillInfo(billNo);
        }
        
        public System.Threading.Tasks.Task<testClient.ServiceReference1.vwICBill_8[]> GetSaleBillInfoAsync(string billNo) {
            return base.Channel.GetSaleBillInfoAsync(billNo);
        }
    }
}
